on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-golang-app:
    runs-on: ubuntu-latest
    steps:

      # Maintain release PR + create GitHub release if merged
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # optional. customize path to release-please-config.json
          config-file: release-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json

      # React to GitHub release created
#      - uses: actions/checkout@v4
#        if: ${{ steps.release.outputs.release_created }}

#      - uses: docker://pandoc/latex:2.9
#        if: ${{ steps.release.outputs.release_created }}
#        with:
#          args: --output=./docs/Documentation.pdf ./docs/README.md ./docs/apache-notice.md

#      - name: Upload Documentation to relase
#        if: ${{ steps.release.outputs.release_created }}
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: gh release upload ${{ steps.release.outputs.tag_name }} docs/Documentation.pdf